version: 1.0.{build}
branches:
  only:
  - master
environment:
  STATIC_SITE_REPO: https://github.com/JaredDC/DailyWallpaperUI
  TARGET_BRANCH: master
  GIT_USER_EMAIL: jared.dcx@gmail.com
  GIT_USER_NAME: JaredDC
image: Visual Studio 2019
configuration: Release
platform: Any CPU
test: off
before_build:
- ps: >-
     nuget restore -verbosity detailed
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
     echo https://www.appveyor.com/docs/environment-variables/
     7z a DailyWallpaper.7z %APPVEYOR_BUILD_FOLDER%\dailywallpaperui\DailyWallpaper\bin\Release
     move DailyWallpaper.7z %APPVEYOR_BUILD_FOLDER%
artifacts:
  - path: dailywallpaperui\DailyWallpaper\bin\Release
    name: DailyWallpaper
  - path: dailywallpaperui/DailyWallpaper/bin/Debug
    name: DailyWallpaperDebug
on_success:
    - echo succeed