version: '{build}'
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
test: off
before_build:
- ps: >-
     nuget Install-Package Microsoft.WindowsAPICodePack-Shell
build:
  parallel: true
  verbosity: normal
on_success:
    - echo "succeed"
