environment:
access_token:
    secure: jjIUlINV2I/vxMzoH/jX11I6/rwEo237ELLgm37s3GdLQV3XkNbtVI/BVXjU4xSD
version: '{build}'
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
test: off
before_build:
- ps: >-
     nuget Install-Package Microsoft.WindowsAPICodePack-Shell
build:
  parallel: true
  verbosity: normal
install:
	- node --version
	- npm --version
on_success:
    - echo "succeed"