version: 1.5.3.{build}
environment:
  STATIC_SITE_REPO: https://github.com/JaredDC/DailyWallpaper
  TARGET_BRANCH: master
  GIT_USER_EMAIL: jared.dcx@gmail.com
  GIT_USER_NAME: JaredDC
image: Visual Studio 2019
configuration: Release
test: off
before_build:
- ps: >-
     nuget restore -verbosity detailed
build:
  parallel: true
  verbosity: minimal
  
after_build:
- cmd:
    dir
    
    7z x v2rayN-Core-bin\v2ray-windows.zip -ov2rayN\bin\Release
    
    cd DailyWallpaper\bin\Release\
    
    7z a DailyWallpaper.Protable.zip .
    
    dir
    
    move DailyWallpaper.zip ..\..\..\OUTPUT


artifacts:
- path: output\DailyWallpaper.Installer.msi
  name: DailyWallpaper.Installer
- path: output\DailyWallpaper.Protable.zip
  name: DailyWallpaper.Protable

deploy:
  release: DailyWallpaper $(APPVEYOR_REPO_TAG_NAME)
  description: "[Changelog](https://github.com/JaredDC/DailyWallpaper/tree/master/Changelogs)"
  provider: GitHub
  auth_token:
    secure:  jjIUlINV2I/vxMzoH/jX11I6/rwEo237ELLgm37s3GdLQV3XkNbtVI/BVXjU4xSD
  artifact: DailyWallpaper.Installer, DailyWallpaper.Protable
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only