version: 1.5.3.{build}
environment:
  STATIC_SITE_REPO: https://github.com/JaredDC/DailyWallpaper
  TARGET_BRANCH: master
  GIT_USER_EMAIL: jared.dcx@gmail.com
  GIT_USER_NAME: JaredDC
image: Visual Studio 2019
configuration: Release
test: off
before_build:
- ps: >-
     nuget restore -verbosity detailed
build:
  parallel: true
  verbosity: minimal
  
after_build:
- cmd:   
    git describe --always --tags >OUTPUTFILE.TXT
    
    set /P GIT_TAG=<OUTPUTFILE.TXT
    
    cd DailyWallpaper\bin\Release\
    
    7z a DailyWallpaper.Protable.zip .
   
    move DailyWallpaper.Protable.zip ..\..\..\OUTPUT\DailyWallpaper.Protable-%GIT_TAG%.zip
    
    cd ..\..\..\OUTPUT
    
    move DailyWallpaper.Installer.msi DailyWallpaper.Installer-%GIT_TAG%.msi
    
    dir


artifacts:
- path: OUTPUT\DailyWallpaper.Installer-%GIT_TAG%.msi
  name: DailyWallpaper.Installer
- path: OUTPUT\DailyWallpaper.Protable-%GIT_TAG%.zip
  name: DailyWallpaper.Protable

deploy:
  release: DailyWallpaper $(APPVEYOR_REPO_TAG_NAME)
  description: "[Changelog](https://github.com/JaredDC/DailyWallpaper/tree/master/Changelogs)"
  provider: GitHub
  auth_token:
    secure:  jjIUlINV2I/vxMzoH/jX11I6/rwEo237ELLgm37s3GdLQV3XkNbtVI/BVXjU4xSD
  artifact: DailyWallpaper.Installer, DailyWallpaper.Protable
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only