environment:
  STATIC_SITE_REPO: https://github.com/JaredDC/DailyWallpaper
  TARGET_BRANCH: master
  GIT_USER_EMAIL: jared.dcx@gmail.com
  GIT_USER_NAME: JaredDC
image: Visual Studio 2019
configuration: Release
test: off
# nuget restore -verbosity detailed 
before_build:
- ps: >-
     nuget restore
build:
  parallel: true
  verbosity: minimal
  
after_build:
- cmd:   
    git describe --always --tags >OUTPUTFILE.TXT
    
    set /P GIT_TAG=<OUTPUTFILE.TXT
    
    cd DailyWallpaper\bin\Release\
    
    7z a DailyWallpaper.Protable.zip .
   
    move DailyWallpaper.Protable.zip ..\..\..\OUTPUT\DailyWallpaper.Protable-%GIT_TAG%.zip
    
    cd ..\..\..\OUTPUT
    
    move DailyWallpaper.Installer.msi DailyWallpaper.Installer-%GIT_TAG%.msi
    
    sha256sum.exe DailyWallpaper.Installer-%GIT_TAG%.msi > DailyWallpaper.Installer-%GIT_TAG%.msi.sha256
    
    sha256sum.exe DailyWallpaper.Protable-%GIT_TAG%.zip > DailyWallpaper.Protable-%GIT_TAG%.zip.sha256
    
    #echo signtool.exe sign /fd SHA256 /n "SHA256" "DailyWallpaper.Protable-%GIT_TAG%.zip" > sign.bat
    #echo signtool.exe sign /fd SHA256 /n "SHA256" "DailyWallpaper.Installer-%GIT_TAG%.msi" >> sign.bat
    #call sign.bat
    
version: DW.{build}

artifacts:
- path: OUTPUT\DailyWallpaper.Installer-%GIT_TAG%.msi
  name: DailyWallpaper.Installer
- path: OUTPUT\DailyWallpaper.Protable-%GIT_TAG%.zip
  name: DailyWallpaper.Protable
- path: OUTPUT\*.msi.sha256
  name: DailyWallpaper.Installer.Hash
- path: OUTPUT\*.zip.sha256
  name: DailyWallpaper.Protable.Hash

deploy:
  release: pre%GIT_TAG%
  description: " NEED ADD "
  provider: GitHub
  auth_token:
    secure:  jjIUlINV2I/vxMzoH/jX11I6/rwEo237ELLgm37s3GdLQV3XkNbtVI/BVXjU4xSD
  artifact: DailyWallpaper.Installer, DailyWallpaper.Protable
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only